version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://127.0.0.1:27017/multiTenantApp

      - JWT_SECRET=581d77639ecc813f25c8b5bb6a209dc03ab6456f0e93dc928b85a73e6c2202d6
      - WEBHOOK_SECRET=webhooksecret
    depends_on:
      - mongo

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
    depends_on:
      - backend

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
